export const WORLD_CITIES = [
  { name: "London", country: "GB", timezone: "Europe/London" },
  { name: "Paris", country: "FR", timezone: "Europe/Paris" },
  { name: "Berlin", country: "DE", timezone: "Europe/Berlin" },
  { name: "Rome", country: "IT", timezone: "Europe/Rome" },
  { name: "Madrid", country: "ES", timezone: "Europe/Madrid" },
  { name: "Athens", country: "GR", timezone: "Europe/Athens" },
  { name: "Cairo", country: "EG", timezone: "Africa/Cairo" },
  { name: "Johannesburg", country: "ZA", timezone: "Africa/Johannesburg" },
  { name: "Moscow", country: "RU", timezone: "Europe/Moscow" },
  { name: "Istanbul", country: "TR", timezone: "Europe/Istanbul" },
  { name: "Riyadh", country: "SA", timezone: "Asia/Riyadh" },
  { name: "Dubai", country: "AE", timezone: "Asia/Dubai" },
  { name: "Karachi", country: "PK", timezone: "Asia/Karachi" },
  { name: "Delhi", country: "IN", timezone: "Asia/Kolkata" },
  { name: "Dhaka", country: "BD", timezone: "Asia/Dhaka" },
  { name: "Bangkok", country: "TH", timezone: "Asia/Bangkok" },
  { name: "Jakarta", country: "ID", timezone: "Asia/Jakarta" },
  { name: "Singapore", country: "SG", timezone: "Asia/Singapore" },
  { name: "Beijing", country: "CN", timezone: "Asia/Shanghai" },
  { name: "Hong Kong", country: "HK", timezone: "Asia/Hong_Kong" },
  { name: "Manila", country: "PH", timezone: "Asia/Manila" },
  { name: "Seoul", country: "KR", timezone: "Asia/Seoul" },
  { name: "Tokyo", country: "JP", timezone: "Asia/Tokyo" },
  { name: "Sydney", country: "AU", timezone: "Australia/Sydney" },
  { name: "Melbourne", country: "AU", timezone: "Australia/Melbourne" },
  { name: "Auckland", country: "NZ", timezone: "Pacific/Auckland" },
  { name: "Honolulu", country: "US", timezone: "Pacific/Honolulu" },
  { name: "Anchorage", country: "US", timezone: "America/Anchorage" },
  { name: "Los Angeles", country: "US", timezone: "America/Los_Angeles" },
  { name: "Vancouver", country: "CA", timezone: "America/Vancouver" },
  { name: "Denver", country: "US", timezone: "America/Denver" },
  { name: "Mexico City", country: "MX", timezone: "America/Mexico_City" },
  { name: "Chicago", country: "US", timezone: "America/Chicago" },
  { name: "New York", country: "US", timezone: "America/New_York" },
  { name: "Toronto", country: "CA", timezone: "America/Toronto" },
  { name: "Bogotá", country: "CO", timezone: "America/Bogota" },
  { name: "Lima", country: "PE", timezone: "America/Lima" },
  { name: "Caracas", country: "VE", timezone: "America/Caracas" },
  { name: "Santiago", country: "CL", timezone: "America/Santiago" },
  { name: "São Paulo", country: "BR", timezone: "America/Sao_Paulo" },
  { name: "Buenos Aires", country: "AR", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Casablanca", country: "MA", timezone: "Africa/Casablanca" },
  { name: "Lagos", country: "NG", timezone: "Africa/Lagos" },
  { name: "Nairobi", country: "KE", timezone: "Africa/Nairobi" },
  { name: "Addis Ababa", country: "ET", timezone: "Africa/Addis_Ababa" },
  { name: "Tehran", country: "IR", timezone: "Asia/Tehran" },
  { name: "Kabul", country: "AF", timezone: "Asia/Kabul" },
  { name: "Colombo", country: "LK", timezone: "Asia/Colombo" },
  { name: "Kathmandu", country: "NP", timezone: "Asia/Kathmandu" },
  { name: "Yangon", country: "MM", timezone: "Asia/Yangon" },
  { name: "Kuala Lumpur", country: "MY", timezone: "Asia/Kuala_Lumpur" },
  { name: "Taipei", country: "TW", timezone: "Asia/Taipei" },
  { name: "Perth", country: "AU", timezone: "Australia/Perth" },
  { name: "Brisbane", country: "AU", timezone: "Australia/Brisbane" },
  { name: "Amsterdam", country: "NL", timezone: "Europe/Amsterdam" },
  { name: "Brussels", country: "BE", timezone: "Europe/Brussels" },
  { name: "Vienna", country: "AT", timezone: "Europe/Vienna" },
  { name: "Warsaw", country: "PL", timezone: "Europe/Warsaw" },
  { name: "Prague", country: "CZ", timezone: "Europe/Prague" },
  { name: "Budapest", country: "HU", timezone: "Europe/Budapest" },
  { name: "Bucharest", country: "RO", timezone: "Europe/Bucharest" },
  { name: "Stockholm", country: "SE", timezone: "Europe/Stockholm" },
  { name: "Copenhagen", country: "DK", timezone: "Europe/Copenhagen" },
  { name: "Oslo", country: "NO", timezone: "Europe/Oslo" },
  { name: "Helsinki", country: "FI", timezone: "Europe/Helsinki" },
  { name: "Dublin", country: "IE", timezone: "Europe/Dublin" },
  { name: "Lisbon", country: "PT", timezone: "Europe/Lisbon" },
  { name: "Zurich", country: "CH", timezone: "Europe/Zurich" },
  { name: "Kiev", country: "UA", timezone: "Europe/Kiev" },
  { name: "Mumbai", country: "IN", timezone: "Asia/Kolkata" },
  { name: "Bangalore", country: "IN", timezone: "Asia/Kolkata" },
  { name: "Shanghai", country: "CN", timezone: "Asia/Shanghai" },
  { name: "Shenzhen", country: "CN", timezone: "Asia/Shanghai" },
  { name: "Guangzhou", country: "CN", timezone: "Asia/Shanghai" },
  { name: "Ho Chi Minh City", country: "VN", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Hanoi", country: "VN", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Phnom Penh", country: "KH", timezone: "Asia/Phnom_Penh" },
  { name: "Vientiane", country: "LA", timezone: "Asia/Vientiane" },
  { name: "Wellington", country: "NZ", timezone: "Pacific/Auckland" },
  { name: "Suva", country: "FJ", timezone: "Pacific/Fiji" },
  { name: "Port Moresby", country: "PG", timezone: "Pacific/Port_Moresby" },
  { name: "Reykjavik", country: "IS", timezone: "Atlantic/Reykjavik" },
  { name: "Accra", country: "GH", timezone: "Africa/Accra" },
  { name: "Dakar", country: "SN", timezone: "Africa/Dakar" },
  { name: "Algiers", country: "DZ", timezone: "Africa/Algiers" },
  { name: "Tunis", country: "TN", timezone: "Africa/Tunis" },
  { name: "Khartoum", country: "SD", timezone: "Africa/Khartoum" },
  { name: "Dar es Salaam", country: "TZ", timezone: "Africa/Dar_es_Salaam" },
  { name: "Kampala", country: "UG", timezone: "Africa/Kampala" },
  { name: "Kigali", country: "RW", timezone: "Africa/Kigali" },
  { name: "Maputo", country: "MZ", timezone: "Africa/Maputo" },
  { name: "Lusaka", country: "ZM", timezone: "Africa/Lusaka" },
  { name: "Harare", country: "ZW", timezone: "Africa/Harare" },
  { name: "Windhoek", country: "NA", timezone: "Africa/Windhoek" },
  { name: "Gaborone", country: "BW", timezone: "Africa/Gaborone" },
  { name: "Doha", country: "QA", timezone: "Asia/Qatar" },
  { name: "Kuwait City", country: "KW", timezone: "Asia/Kuwait" },
  { name: "Manama", country: "BH", timezone: "Asia/Bahrain" },
  { name: "Muscat", country: "OM", timezone: "Asia/Muscat" },
  { name: "Abu Dhabi", country: "AE", timezone: "Asia/Dubai" },
  { name: "Amman", country: "JO", timezone: "Asia/Amman" },
  { name: "Beirut", country: "LB", timezone: "Asia/Beirut" },
  { name: "Damascus", country: "SY", timezone: "Asia/Damascus" },
  { name: "Baghdad", country: "IQ", timezone: "Asia/Baghdad" },
  { name: "Jerusalem", country: "IL", timezone: "Asia/Jerusalem" },
  { name: "Tbilisi", country: "GE", timezone: "Asia/Tbilisi" },
  { name: "Yerevan", country: "AM", timezone: "Asia/Yerevan" },
  { name: "Baku", country: "AZ", timezone: "Asia/Baku" },
  { name: "Tashkent", country: "UZ", timezone: "Asia/Tashkent" },
  { name: "Almaty", country: "KZ", timezone: "Asia/Almaty" },
  { name: "Bishkek", country: "KG", timezone: "Asia/Bishkek" },
  { name: "Dushanbe", country: "TJ", timezone: "Asia/Dushanbe" },
  { name: "Ashgabat", country: "TM", timezone: "Asia/Ashgabat" },
  { name: "Ulaanbaatar", country: "MN", timezone: "Asia/Ulaanbaatar" },
  { name: "Pyongyang", country: "KP", timezone: "Asia/Pyongyang" },
  { name: "Vladivostok", country: "RU", timezone: "Asia/Vladivostok" },
  { name: "Novosibirsk", country: "RU", timezone: "Asia/Novosibirsk" },
  { name: "Yekaterinburg", country: "RU", timezone: "Asia/Yekaterinburg" },
  { name: "Montreal", country: "CA", timezone: "America/Toronto" },
  { name: "Ottawa", country: "CA", timezone: "America/Toronto" },
  { name: "Calgary", country: "CA", timezone: "America/Edmonton" },
  { name: "Edmonton", country: "CA", timezone: "America/Edmonton" },
  { name: "Winnipeg", country: "CA", timezone: "America/Winnipeg" },
  { name: "Quebec City", country: "CA", timezone: "America/Toronto" },
  { name: "Halifax", country: "CA", timezone: "America/Halifax" },
  { name: "Boston", country: "US", timezone: "America/New_York" },
  { name: "Philadelphia", country: "US", timezone: "America/New_York" },
  { name: "Washington DC", country: "US", timezone: "America/New_York" },
  { name: "Miami", country: "US", timezone: "America/New_York" },
  { name: "Atlanta", country: "US", timezone: "America/New_York" },
  { name: "Houston", country: "US", timezone: "America/Chicago" },
  { name: "Dallas", country: "US", timezone: "America/Chicago" },
  { name: "Phoenix", country: "US", timezone: "America/Phoenix" },
  { name: "Las Vegas", country: "US", timezone: "America/Los_Angeles" },
  { name: "San Francisco", country: "US", timezone: "America/Los_Angeles" },
  { name: "Seattle", country: "US", timezone: "America/Los_Angeles" },
  { name: "San Diego", country: "US", timezone: "America/Los_Angeles" },
  { name: "Portland", country: "US", timezone: "America/Los_Angeles" },
  { name: "San Antonio", country: "US", timezone: "America/Chicago" },
  { name: "Minneapolis", country: "US", timezone: "America/Chicago" },
  { name: "Detroit", country: "US", timezone: "America/Detroit" },
  { name: "Guadalajara", country: "MX", timezone: "America/Mexico_City" },
  { name: "Monterrey", country: "MX", timezone: "America/Monterrey" },
  { name: "Tijuana", country: "MX", timezone: "America/Tijuana" },
  { name: "Guatemala City", country: "GT", timezone: "America/Guatemala" },
  { name: "San Salvador", country: "SV", timezone: "America/El_Salvador" },
  { name: "Managua", country: "NI", timezone: "America/Managua" },
  { name: "San José", country: "CR", timezone: "America/Costa_Rica" },
  { name: "Panama City", country: "PA", timezone: "America/Panama" },
  { name: "Havana", country: "CU", timezone: "America/Havana" },
  { name: "Kingston", country: "JM", timezone: "America/Jamaica" },
  { name: "Port-au-Prince", country: "HT", timezone: "America/Port-au-Prince" },
  { name: "Santo Domingo", country: "DO", timezone: "America/Santo_Domingo" },
  { name: "San Juan", country: "PR", timezone: "America/Puerto_Rico" },
  { name: "Bridgetown", country: "BB", timezone: "America/Barbados" },
  { name: "Port of Spain", country: "TT", timezone: "America/Port_of_Spain" },
  { name: "Quito", country: "EC", timezone: "America/Guayaquil" },
  { name: "La Paz", country: "BO", timezone: "America/La_Paz" },
  { name: "Asunción", country: "PY", timezone: "America/Asuncion" },
  { name: "Montevideo", country: "UY", timezone: "America/Montevideo" },
  { name: "Rio de Janeiro", country: "BR", timezone: "America/Sao_Paulo" },
  { name: "Brasília", country: "BR", timezone: "America/Sao_Paulo" },
  { name: "Manaus", country: "BR", timezone: "America/Manaus" },
  { name: "Fortaleza", country: "BR", timezone: "America/Fortaleza" },
  { name: "Recife", country: "BR", timezone: "America/Recife" },
  { name: "Adelaide", country: "AU", timezone: "Australia/Adelaide" },
  { name: "Canberra", country: "AU", timezone: "Australia/Sydney" },
  { name: "Hobart", country: "AU", timezone: "Australia/Hobart" },
  { name: "Darwin", country: "AU", timezone: "Australia/Darwin" },
];

export const getCityTime = (timezone: string) => {
    return new Date().toLocaleTimeString('en-US', {
        timeZone: timezone,
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
    })
}

// Get time difference from user's timezone
export const getTimeDifference = (timezone: string) => {
    const userTime = new Date();
    const cityTime = new Date(userTime.toLocaleString('en-US', { timeZone: timezone }))
    const diffHours = (cityTime.getTime() - userTime.getTime()) / (1000 * 60 * 60);

    if (diffHours === 0) return 'Same time';

    const word = diffHours > 0 ? 'ahead' : 'behind'
    
    return `${diffHours} hours ${word}`;
}